### ISSUE TITLE
Add Server ID in JSON Output

### ISSUE THREAD

**Issue by aweberlopes** [racoon63/bandwidth-monitor#10]
Hello Patrick,

it would be nice if you can add to json output a serverID or serverName flag.

That can help to sort it Grafana if you set auto as server.

Thanks 
Alex Weber Lopes

```
{
    "bwm": {
        "1": {
            "download": 24.99,
            "ping": 38.49,
            "timestamp": "2020-03-07-16-22-13",
            "upload": 13.02,
            "serverID": 1234,
            "serverName: "Frankfurt"
        }
    }
}
```

**Comment by racoon63** [comment]
Hello Alex,

thank you for your request. The measurement contains now much more information including the server ID.

Regards
Patrick
