### ISSUE TITLE
implement InfluxDB as DataBase Module 

### ISSUE THREAD

**Issue by aweberlopes** [racoon63/bandwidth-monitor#24]
InfluxDB as TimeSeries DB for BWM would be awesome. Implementing a similiar module like mongo db one shouldn't be a big deal. 
 I would try to implement this module.

**Comment by aweberlopes** [comment]
#27 created

**Comment by racoon63** [comment]
I will have a look at this. Stay tuned!

**Comment by racoon63** [comment]
Was merged. Will be closed.
