### ISSUE TITLE
Add InfluxDB in docker-compose 

### ISSUE THREAD

**Issue by aweberlopes** [racoon63/bandwidth-monitor#25]
I would extend the docker-compose to deploy a basic config of influxDB to put data inside.

**Comment by aweberlopes** [comment]
https://github.com/jkehres/docker-compose-influxdb-grafana

**Comment by racoon63** [comment]
Is related to #27

**Comment by racoon63** [comment]
In which commit are the changes? Please link them here.

**Comment by aweberlopes** [comment]
is related to # #34

**Comment by racoon63** [comment]
Do you plan to add Chronograf in the future?

**Comment by aweberlopes** [comment]
I would start with grafana is more flexible if we use multiple datasource types. Chronograph is binded to Influx.

**Comment by racoon63** [comment]
Yes, you are right. Can be closed through PR #34.
